name: Copilot Setup Steps

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Run preview page
        run: npm run preview
        shell: bash
